general:
  states: [st_drive_percent]
  subsystems: [ss_drive]
  boolean_inputs: [bi_driver_left_trigger]
  numeric_inputs: [ni_driver_left_y, ni_driver_right_x]
  vector_inputs: []
  motors: [mo_drive_left, mo_drive_right]
  solenoids: [so_drive_gear]

global_timing:
  frame_time_threshold_input_service: 80
  frame_time_threshold_logging_service: 80
  frame_time_threshold_output_service: 80
  frame_time_threshold_state_service: 80
  frame_time_threshold_webdashboard_service: 80
  frame_cycle_time_threshold_input_service: 80
  frame_cycle_time_threshold_logging_service: 80
  frame_cycle_time_threshold_output_service: 80
  frame_cycle_time_threshold_state_service: 80
  frame_cycle_time_threshold_webdashboard_service: 80

log:
  ni_driver_x: true
  ni_driver_y: true
  bi_driver_left_trigger: true
  ni_climb_vacuum_sensor: true

global_drive:
  x: ni_driver_right_x
  y: ni_driver_left_y
  gear_shift_button: bi_driver_left_trigger

web_dashboard_match_values:
  bi_driver_left_trigger:
    type: boolean
    display_name: Test Value